CXX = g++
CFLAGS = -std=c++11
Include = -I.

.PHONY: clean Simple Iterator Alternative

all: Simple Iterator Alternative

Simple:
	run.bat Simple

Iterator:
	run.bat Iterator

Alternative:
	run.bat Alternative

clean:
	@del *.o
	@del *.exe